name: CI/CD Pipeline to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  # Instead of writing the test steps here, we just point to the template!
  call-the-tester:
    uses: ./.github/workflows/multjob.yml
